name: login_page
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  static_analyze_av: ^0.4.1

dev_dependencies:
  flutter_bloc: ^8.0.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: RubikB
      fonts:
        - asset: fonts/Rubik-Bold.ttf
    - family: RubikR
      fonts:
        - asset: fonts/Rubik-Regular.ttf
    - family: RubikSB
      fonts:
        - asset: fonts/Rubik-SemiBold.ttf
  assets:
    - images/apple.png
    - images/facebook.png
    - images/google.png
    - images/logo.png
  uses-material-design: true